#!/usr/bin/env python
import os
import csv
import math
import itertools
from pathlib import Path

import numpy as np
from scipy.ndimage import distance_transform_edt
from skimage.measure import marching_cubes


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent

# Everything generated by this script is stored here.
OUTPUT_DIR = PROJECT_ROOT / "implicit_bspline_dataset" / "volumes"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

VOLUME_SHARD_DIR = OUTPUT_DIR / "volume_shards"
MESH_DIR = OUTPUT_DIR / "meshes"

VOLUME_SHARD_DIR.mkdir(parents=True, exist_ok=True)
MESH_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Grid / world-space convention
# ------------------------------------------------------------
#
# The generated sampled field occupies world space:
#
#     [-0.5, 0.5]^3
#
# Samples include both endpoints. Thus voxel spacing is:
#
#     1 / (GRID_N - 1)
#
# ------------------------------------------------------------

GRID_NX = 64
GRID_NY = 64
GRID_NZ = 64

DOMAIN_MIN = -0.5
DOMAIN_MAX = 0.5

# A 2x2x2 control lattice uses degree-1 basis functions:
# trilinear interpolation.
DEG_X = 1
DEG_Y = 1
DEG_Z = 1

NZ_CTRL = 2
NY_CTRL = 2
NX_CTRL = 2

# ------------------------------------------------------------
# Four coefficient levels: two negative and two positive.
#
# np.linspace(-0.5, 0.5, 4) gives:
# [-0.5, -0.16666667, 0.16666667, 0.5]
#
# There is intentionally no exact zero coefficient level.
# ------------------------------------------------------------

CTRL_MIN = -0.5
CTRL_MAX = 0.5
NUM_CTRL_LEVELS = 4

# Number of unique control grids/geometries to retain.
#
# With five sigma values:
#     10,000 geometries x 5 sigmas = 50,000 volumes.
TARGET_NUM_GEOMETRIES = 10000

# Makes the selected subset deterministic/reproducible.
GEOMETRY_SELECTION_SEED = 2025

# Gaussian thicknesses in world-space units.
SIGMA_VALUES = [0.02, 0.08, 0.20, 0.50, 0.70]

# Number of volumes packed into each .npy shard.
#
# One 64^3 float32 volume is 1 MiB:
#     64 * 64 * 64 * 4 bytes = 1,048,576 bytes
#
# Thus:
#     128 volumes/shard ≈ 128 MiB/shard.
#
# 50,000 volumes produce about 391 shard files.
VOLUME_SHARD_SIZE = 1024

COEFF_MEAN = 0.0
COEFF_STD = 1.0


# ============================================================
# IMPLICIT 2x2x2 B-SPLINE / TRILINEAR FIELD
# ============================================================

def trilinear_bspline_field(control_grid, xs, ys, zs):
    """
    Evaluate a degree-(1,1,1) tensor-product B-spline with a 2x2x2
    control grid. With two controls per axis, this is trilinear
    interpolation.

    Parameters
    ----------
    control_grid : ndarray, shape (2, 2, 2)
        Indexed as control_grid[z_control, y_control, x_control].

    xs, ys, zs : 1D ndarrays
        Normalized interpolation coordinates in [0, 1].

    Returns
    -------
    field : ndarray, shape (nx, ny, nz)
        The implicit surface is field == 0.
    """
    if control_grid.shape != (2, 2, 2):
        raise ValueError(
            f"Expected control-grid shape (2, 2, 2), got {control_grid.shape}"
        )

    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")

    c000 = control_grid[0, 0, 0]
    c001 = control_grid[0, 0, 1]
    c010 = control_grid[0, 1, 0]
    c011 = control_grid[0, 1, 1]

    c100 = control_grid[1, 0, 0]
    c101 = control_grid[1, 0, 1]
    c110 = control_grid[1, 1, 0]
    c111 = control_grid[1, 1, 1]

    # Interpolate along x.
    c00 = (1.0 - X) * c000 + X * c001
    c01 = (1.0 - X) * c010 + X * c011
    c10 = (1.0 - X) * c100 + X * c101
    c11 = (1.0 - X) * c110 + X * c111

    # Interpolate along y.
    c0 = (1.0 - Y) * c00 + Y * c01
    c1 = (1.0 - Y) * c10 + Y * c11

    # Interpolate along z.
    field = (1.0 - Z) * c0 + Z * c1

    return field.astype(np.float32)


def approximate_signed_distance(field, voxel_spacing):
    """
    Build an approximate signed-distance field in world-space units.

    Negative side: field < 0
    Positive side: field >= 0

    Returns None if the sampled field has no sign change.
    """
    inside = field < 0.0

    if np.all(inside) or not np.any(inside):
        return None

    distance_to_inside = distance_transform_edt(
        ~inside,
        sampling=voxel_spacing,
    )

    distance_to_outside = distance_transform_edt(
        inside,
        sampling=voxel_spacing,
    )

    # Negative inside, positive outside.
    sdf = distance_to_inside - distance_to_outside

    return sdf.astype(np.float32)


def build_volume(control_grid, sigma):
    """
    Construct:
        F   : implicit trilinear field
        SDF : approximate signed-distance field, in world units
        V   : Gaussian density shell around F=0

    Stored density:
        V = exp(-0.5 * (SDF / sigma)^2)
    """
    u = np.linspace(0.0, 1.0, GRID_NX, dtype=np.float32)
    v = np.linspace(0.0, 1.0, GRID_NY, dtype=np.float32)
    w = np.linspace(0.0, 1.0, GRID_NZ, dtype=np.float32)

    # World coordinates for marching-cubes spacing.
    world_x = np.linspace(DOMAIN_MIN, DOMAIN_MAX, GRID_NX, dtype=np.float32)
    world_y = np.linspace(DOMAIN_MIN, DOMAIN_MAX, GRID_NY, dtype=np.float32)
    world_z = np.linspace(DOMAIN_MIN, DOMAIN_MAX, GRID_NZ, dtype=np.float32)

    spacing = (
        float(world_x[1] - world_x[0]),
        float(world_y[1] - world_y[0]),
        float(world_z[1] - world_z[0]),
    )

    field = trilinear_bspline_field(control_grid, u, v, w)

    field_min = float(field.min())
    field_max = float(field.max())

    # Require 0 to lie strictly in the sampled range.
    if not (field_min < 0.0 < field_max):
        return None, None, spacing

    sdf = approximate_signed_distance(
        field=field,
        voxel_spacing=spacing,
    )

    if sdf is None:
        return None, None, spacing

    sigma = float(sigma)

    if sigma <= 0.0:
        raise ValueError(f"sigma must be positive, got {sigma}")

    volume = np.exp(-0.5 * (sdf / sigma) ** 2).astype(np.float32)

    return field, volume, spacing


# ============================================================
# CONTROL-GRID SELECTION
# ============================================================

def all_valid_control_grids():
    """
    Enumerate every valid four-level 2x2x2 control grid.

    With levels:
        [-0.5, -0.1667, 0.1667, 0.5]

    a grid is valid if it has at least one negative and one positive
    corner coefficient.

    Total valid grids:
        4^8 - 2^8 - 2^8 = 65,024.
    """
    ctrl_levels = np.linspace(
        CTRL_MIN,
        CTRL_MAX,
        NUM_CTRL_LEVELS,
        dtype=np.float32,
    )

    valid_grids = []

    for values in itertools.product(
        ctrl_levels,
        repeat=NZ_CTRL * NY_CTRL * NX_CTRL,
    ):
        control_grid = np.asarray(
            values,
            dtype=np.float32,
        ).reshape(NZ_CTRL, NY_CTRL, NX_CTRL)

        has_negative = np.any(control_grid < 0.0)
        has_positive = np.any(control_grid > 0.0)

        if has_negative and has_positive:
            valid_grids.append(control_grid)

    return valid_grids


def select_control_grids():
    """
    Deterministically choose TARGET_NUM_GEOMETRIES valid control grids.
    """
    valid_grids = all_valid_control_grids()

    print(f"Total valid sign-changing control grids: {len(valid_grids):,}")

    if TARGET_NUM_GEOMETRIES > len(valid_grids):
        raise ValueError(
            f"TARGET_NUM_GEOMETRIES={TARGET_NUM_GEOMETRIES:,} exceeds "
            f"the number of valid grids={len(valid_grids):,}"
        )

    rng = np.random.RandomState(GEOMETRY_SELECTION_SEED)

    selected_indices = rng.choice(
        len(valid_grids),
        size=TARGET_NUM_GEOMETRIES,
        replace=False,
    )

    # Sort for deterministic output ordering independent of NumPy internals.
    selected_indices.sort()

    selected_grids = [
        valid_grids[index]
        for index in selected_indices
    ]

    return selected_grids


# ============================================================
# MAIN
# ============================================================

def main():
    metadata_path = OUTPUT_DIR / "metadata_volumes.csv"

    # One row per geometry/sigma volume sample.
    #
    # coeff_path is retained as an empty compatibility column for render
    # scripts that expect it. Coefficients are actually stored directly
    # in ctrl_* CSV columns, so separate coefficient files are unnecessary.
    fieldnames = [
        "sample_id",
        "geometry_id",
        "coeff_path",
        "mesh_path",
        "volume_shard_path",
        "volume_idx_in_shard",
        "deg_x",
        "deg_y",
        "deg_z",
        "grid_nx",
        "grid_ny",
        "grid_nz",
        "domain_min",
        "domain_max",
        "coeff_mean",
        "coeff_std",
        "isovalue",
        "sigma",
    ]

    for z_idx in range(NZ_CTRL):
        for y_idx in range(NY_CTRL):
            for x_idx in range(NX_CTRL):
                fieldnames.append(f"ctrl_{z_idx}_{y_idx}_{x_idx}")

    selected_grids = select_control_grids()

    expected_volumes = len(selected_grids) * len(SIGMA_VALUES)
    expected_shards = math.ceil(expected_volumes / VOLUME_SHARD_SIZE)

    print("=" * 70)
    print(f"Selected geometries: {len(selected_grids):,}")
    print(f"Sigma values: {SIGMA_VALUES}")
    print(f"Expected volumes: {expected_volumes:,}")
    print(f"Volume shard size: {VOLUME_SHARD_SIZE}")
    print(f"Expected volume shard files: {expected_shards:,}")
    print("=" * 70)

    with open(metadata_path, "w", newline="") as f_meta:
        writer = csv.DictWriter(
            f_meta,
            fieldnames=fieldnames,
        )
        writer.writeheader()

        volume_buffer = []
        pending_rows = []
        volume_shard_id = 0

        def flush_volume_shard():
            """
            Save buffered volumes as one NPY file, then write their CSV rows.

            Each shard has shape:
                (num_volumes_in_this_shard, GRID_NX, GRID_NY, GRID_NZ)
            """
            nonlocal volume_buffer
            nonlocal pending_rows
            nonlocal volume_shard_id

            if not volume_buffer:
                return

            volume_shard = np.stack(
                volume_buffer,
                axis=0,
            ).astype(np.float32)

            shard_path = VOLUME_SHARD_DIR / (
                f"volume_shard_{volume_shard_id:06d}.npy"
            )

            np.save(shard_path, volume_shard)

            for idx_in_shard, metadata_row in enumerate(pending_rows):
                metadata_row["volume_shard_path"] = str(shard_path)
                metadata_row["volume_idx_in_shard"] = int(idx_in_shard)
                writer.writerow(metadata_row)

            print(
                f"[VOLUME SHARD {volume_shard_id:06d}] "
                f"saved {len(volume_buffer)} volumes: "
                f"{shard_path.name}, shape={volume_shard.shape}"
            )

            volume_shard_id += 1
            volume_buffer = []
            pending_rows = []

        sample_id = 0

        for geometry_index, control_grid in enumerate(selected_grids):
            geometry_id = geometry_index + 1

            # ------------------------------------------------
            # Create one mesh per geometry.
            #
            # The F=0 mesh is independent of sigma, so it should
            # not be saved five times.
            # ------------------------------------------------

            field_for_mesh, _, spacing = build_volume(
                control_grid=control_grid,
                sigma=SIGMA_VALUES[0],
            )

            if field_for_mesh is None:
                print(
                    f"[SKIP] geometry_id={geometry_id}: "
                    "no valid sampled F=0 surface"
                )
                continue

            try:
                verts, faces, normals, values = marching_cubes(
                    field_for_mesh,
                    level=0.0,
                    spacing=spacing,
                )
            except RuntimeError as exc:
                print(
                    f"[SKIP] geometry_id={geometry_id}: "
                    f"marching_cubes failed: {exc}"
                )
                continue

            # marching_cubes begins at (0, 0, 0).
            # Shift vertices into world domain [-0.5, 0.5]^3.
            verts -= np.array(
                [
                    -DOMAIN_MIN,
                    -DOMAIN_MIN,
                    -DOMAIN_MIN,
                ],
                dtype=np.float32,
            )

            # Since DOMAIN_MIN = -0.5, this subtracts (0.5, 0.5, 0.5).
            mesh_path = MESH_DIR / f"mesh_geom_{geometry_id:06d}.npz"

            np.savez(
                mesh_path,
                verts=verts.astype(np.float32),
                faces=faces.astype(np.int32),
            )

            # ------------------------------------------------
            # Generate one Gaussian volume for every sigma.
            # ------------------------------------------------

            for sigma in SIGMA_VALUES:
                _, volume, _ = build_volume(
                    control_grid=control_grid,
                    sigma=sigma,
                )

                if volume is None:
                    print(
                        f"[SKIP] geometry_id={geometry_id}, "
                        f"sigma={sigma:.4f}: volume construction failed"
                    )
                    continue

                sample_id += 1

                metadata_row = {
                    "sample_id": sample_id,
                    "geometry_id": geometry_id,

                    # Kept for compatibility with old render metadata code.
                    # All coefficient values are stored in ctrl_* columns.
                    "coeff_path": "",

                    # Same mesh is referenced by every sigma variant.
                    "mesh_path": str(mesh_path),

                    # Filled in by flush_volume_shard().
                    "volume_shard_path": "",
                    "volume_idx_in_shard": "",

                    "deg_x": DEG_X,
                    "deg_y": DEG_Y,
                    "deg_z": DEG_Z,

                    "grid_nx": GRID_NX,
                    "grid_ny": GRID_NY,
                    "grid_nz": GRID_NZ,

                    "domain_min": DOMAIN_MIN,
                    "domain_max": DOMAIN_MAX,

                    "coeff_mean": COEFF_MEAN,
                    "coeff_std": COEFF_STD,

                    "isovalue": 0.0,
                    "sigma": float(sigma),
                }

                for z_idx in range(NZ_CTRL):
                    for y_idx in range(NY_CTRL):
                        for x_idx in range(NX_CTRL):
                            metadata_row[
                                f"ctrl_{z_idx}_{y_idx}_{x_idx}"
                            ] = float(control_grid[z_idx, y_idx, x_idx])

                volume_buffer.append(volume.astype(np.float32))
                pending_rows.append(metadata_row)

                if len(volume_buffer) >= VOLUME_SHARD_SIZE:
                    flush_volume_shard()

            if geometry_id % 100 == 0:
                print(
                    f"[GEOMETRY {geometry_id}/{len(selected_grids)}] "
                    f"processed; samples written/buffered={sample_id:,}"
                )

        # Save the final partially-filled volume shard.
        flush_volume_shard()

    print("=" * 70)
    print("Done.")
    print(f"Metadata CSV: {metadata_path}")
    print(f"Volume shards: {VOLUME_SHARD_DIR}")
    print(f"Meshes: {MESH_DIR}")
    print(f"Total volume samples saved: {sample_id:,}")
    print("=" * 70)


if __name__ == "__main__":
    main()